# Generated by Django 4.2.2 on 2023-06-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResto', '0001_initial'),
    ]

    operations = [
    ]
