# Generated by Django 4.2.2 on 2023-06-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_restaurant_cuisine_type_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='quarter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
