# Generated by Django 4.2.2 on 2023-06-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_table_description_table_image_table_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
