# Generated by Django 4.2.2 on 2023-06-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_restaurant_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='website',
        ),
    ]
